export const data = [
  {
    tierName: "Gold Sponsors",
    data: [
      {
        sponsorName: "Sponser",
        webp: "../../assets/images.png",
        src: "../../assets/2112.w026.n002.1265B.p1.1265.jpg",
        url: "../../assets/images.png",
        id: "gold_0",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "gold_1",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "gold_2",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "gold_3",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "gold_4",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "gold_5",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "gold_6",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "gold_7",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "gold_8",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "gold_9",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "gold_10",
      },
    ],
    id: "1",
  },
  {
    tierName: "Silver Sponsors",
    data: [
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "silver_0",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "silver_1",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "silver_2",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "silver_3",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "silver_4",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "silver_5",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "silver_6",
      },
      {
        sponsorName: "Sponser",
        webp: "../../assets/spec_logo.webp",
        src: "../../assets/spec_logo.webp",
        url: "../../assets/spec_logo.webp",
        id: "silver_7",
      },
    ],
    id: "2",
  },
  {
    tierName: "Bronze Sponsors",
    data: [
      {
        sponsorName: "Jdoodle",
        webp: "sponsors/bronze/webp/Jdoodle.webp",
        src: "sponsors/bronze/Jdoodle.png",
        url: "https://www.jdoodle.com/",
        id: "bronze_1",
      },
      {
        sponsorName: "Give My Certificate",
        webp: "sponsors/bronze/webp/givemycertificate.webp",
        src: "sponsors/bronze/givemycertificate.png",
        url: "https://givemycertificate.com/",
        id: "bronze_2",
      },
      {
        sponsorName: "Interview Buddy",
        webp: "sponsors/bronze/webp/interviewbuddy.webp",
        src: "sponsors/bronze/interviewbuddy.png",
        url: "https://interviewbuddy.in/",
        id: "bronze_3",
      },
      {
        sponsorName: "Coil",
        webp: "sponsors/bronze/webp/coil.webp",
        src: "sponsors/bronze/coil.png",
        url: "https://coil.com/",
        id: "bronze_4",
      },
    ],
    id: "3",
  },
  {
    tierName: "Our Partners",
    data: [
      {
        sponsorName: "GrabOn",
        webp: "sponsors/other/webp/grabon.webp",
        src: "sponsors/other/grabon.png",
        url: "https://www.grabon.in/",
        id: "title_2",
      },
      {
        sponsorName: "NoticeBard",
        webp: "sponsors/other/webp/noticebard.webp",
        src: "sponsors/other/noticebard.png",
        url: "https://www.noticebard.com/",
        id: "title_3",
      },
      {
        sponsorName: "StreamYard",
        webp: "sponsors/other/webp/streamyard.webp",
        src: "sponsors/other/streamyard.png",
        url: "https://streamyard.com/",
        id: "title_4",
      },
      {
        sponsorName: "LeadingLearners",
        webp: "sponsors/other/webp/leadinglearners.webp",
        src: "sponsors/other/leadinglearners.png",
        url: "http://linktr.ee/leadinglearners",
        id: "title_5",
      },
    ],
    id: "4",
  },
  {
    tierName: "Title Sponsors",
    data: [
      {
        sponsorName: "GitHub",
        webp: "sponsors/title/webp/Github.webp",
        src: "sponsors/title/Github.png",
        url: "https://github.com/",
        id: "title_0",
      },
      {
        sponsorName: "GitLab",
        webp: "sponsors/title/webp/gitlab.webp",
        src: "sponsors/title/gitlab.png",
        url: "https://about.gitlab.com/",
        id: "title_1",
      },
      {
        sponsorName: "The @ Company",
        webp: "sponsors/title/webp/atcomp.webp",
        src: "sponsors/title/atcomp.png",
        url: "https://atsign.com/",
        id: "title_2",
      },
    ],
    id: "0",
  },
];
